insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('015', 'Whispers of Hope', 2070, 'I', 125, 'cyberpunk');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('020', 'Shadows of the Past', 2050, 'X', 150, 'documentary');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('004', 'The Enchanted Mirror', 2028, 'U', 160, 'mystery');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('007', 'Lost in Time', 2005, 'E', 45, 'documentary');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('011', 'The Eternal Flame', 2010, 'DD', 125, 'biography');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('001', 'Echoes of the Soul', 2023, 'K', 40, 'superhero');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('001', 'Whispers in the Dark', 2000, 'W', 100, 'zombie');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('016', 'Echoes of Adventure', 2075, 'J', 50, 'animation');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('014', 'Whispers of the Night', 1990, 'GG', 140, 'crime');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('032', 'The Enchanted Forest', 2005, 'O', 30, 'action');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('018', 'The Secret Chamber', 2028, 'L', 155, 'cyberpunk');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('019', 'Voices in the Mist', 2048, 'GG', 155, 'sports');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('036', 'Echoes of Adventure', 2013, 'C', 20, 'drama');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('033', 'The Hidden Treasure', 2068, 'X', 155, 'heist');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('033', 'Echoes of Serenity', 2028, 'EE', 140, 'historical');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('013', 'Whispers in the Dark', 1990, 'U', 80, 'superhero');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('023', 'The Secret Garden', 2055, 'D', 40, 'noir');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('035', 'The Last Sunrise', 2013, 'G', 185, 'comedy');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('006', 'Echoes of the Heart', 2073, 'FF', 140, 'noir');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('033', 'Echoes of Serenity', 2043, 'R', 60, 'historical');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('004', 'The Crystal Moon', 1998, 'Q', 80, 'musical comedy');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('017', 'Echoes of Magic', 2020, 'Q', 140, 'coming-of-age');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('020', 'The Enchanted Mirror', 2030, 'E', 180, 'romance');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('037', 'The Final Frontier', 2055, 'O', 100, 'biography');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('017', 'Echoes of the Soul', 2023, 'H', 45, 'mockumentary');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('011', 'Echoes of the Heart', 1998, 'Y', 90, 'post-apocalyptic');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('002', 'Echoes of Serenity', 1990, 'C', 55, 'mystery');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('004', 'Echoes of the Soul', 2008, 'GG', 90, 'documentary');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('017', 'Echoes of Eternity', 2030, 'Y', 20, 'buddy cop');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('035', 'Whispers of Love', 1995, 'W', 35, 'horror');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('007', 'Echoes of the Heart', 2018, 'HH', 180, 'time travel');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('036', 'The Final Frontier', 2023, 'GG', 25, 'thriller');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('012', 'Echoes of Serenity', 2050, 'H', 90, 'time travel');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('031', 'Whispers in the Dark', 2028, 'D', 20, 'cyberpunk');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('037', 'The Hidden Treasure', 2045, 'DD', 175, 'documentary');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('036', 'Echoes of Adventure', 2050, 'F', 120, 'cyberpunk');
insert into tblfilms1 (filmID, title, yearReleased, rating, duration, genre) values ('012', 'The Secret Chamber', 2010, 'W', 160, 'found footage');
